import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'
import AarayData from './Components/AarayData'
import Aaray2data from './Components/aaray2data'
import Form from './Components/Form'
import Newform from './Components/Newform'
import Lastform from './Components/Lastform'
import Secondform from './Components/Secondform'
import Thirdform from './Components/Thirdform'


function App() {
    const [count, setCount] = useState(0)
  // const [count, setCount] = useState(0)
// const Data={
//   f_name:"shubham",
//   l_name:"singh",
//   age:24,
// }
//  const person_data=function(){
//   return Data.f_name+" "+Data.l_name+" "+Data.age
// }
//  calculator
// function calculate (a,b){
//   const add = a+b
//   const sub = a-b
//   const mul = a*b
//   const div = a/b
//   const mod = a%b

//   return {add,sub,mul,div,mod}
// }
//   const result = calculate(2, 3);

// spread operator---
// const number1=[1,2,3,4]
// const number2=[5,6,7,8]

// const number3=[...number1,...number2]

//  spread operator with cocatenate-----

const url1="https://react.dev/"

const url2="https://react-icons.github.io/react-icons/search/#q=thun"


 const handleclick =()=>{
     console.log("ha yahi to tha")


    alert("bhaiya btn click ho gya")





 }
 const handler =()=>{
    console.log("seen on console window")

    alert("alert on window")
 }


const product_list= [
            {
                "quantity": "50",
                "price": 15990.0,
                "whishlist_status": "Login Required",
                "variant_id": 5275,
                "variant_name": "vivo T1 5G (Starlight Black, 128 GB)  (4 GB RAM)",
                "actual_price": 15990.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/New_Project_46_2GUElU1.jpg",
                "color_variant_id": 1421,
                "color_variant_name": "Starlight Black",
                "storage_variant_id": 168,
                "storage_variant_name": "128 GB",
                "other_variant_id": 97,
                "other_variant_name": "4 GB",
                "stock_sataus": "In-stock",
                "id": 3318,
                "Meta_Title": "vivo T1 5G",
                "Meta_Keyword": "vivo T1 5G",
                "Meta_Description": "vivo T1 5G",
                "title": "vivo T1 5G",
                "HSN": "18999",
                "description": "vivo T1 5G",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-04-09T19:05:41.358677",
                "permission": 1,
                "slug": "vivo-t1-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 192,
                "sub_category": "Vivo",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 232,
                "brand_name": "VIVO",
                "store_id": 1
            },
            {
                "quantity": "50",
                "price": 15990.0,
                "whishlist_status": "Login Required",
                "variant_id": 5277,
                "variant_name": "vivo T1 5G (Rainbow Fantasy, 128 GB)  (4 GB RAM)",
                "actual_price": 15990.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Crazzyhub_images_1_c1APxjy.jpg",
                "color_variant_id": 1444,
                "color_variant_name": "Rainbow Fantastic ",
                "storage_variant_id": 168,
                "storage_variant_name": "128 GB",
                "other_variant_id": 97,
                "other_variant_name": "4 GB",
                "stock_sataus": "In-stock",
                "id": 3318,
                "Meta_Title": "vivo T1 5G",
                "Meta_Keyword": "vivo T1 5G",
                "Meta_Description": "vivo T1 5G",
                "title": "vivo T1 5G",
                "HSN": "18999",
                "description": "vivo T1 5G",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-04-09T19:05:41.358677",
                "permission": 1,
                "slug": "vivo-t1-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 192,
                "sub_category": "Vivo",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 232,
                "brand_name": "VIVO",
                "store_id": 1
            },
            {
                "quantity": "50",
                "price": 24999.0,
                "whishlist_status": "Login Required",
                "variant_id": 5278,
                "variant_name": "vivo T1 Pro 5G (Turbo Cyan, 128 GB)  (8 GB RAM)",
                "actual_price": 24999.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-t1-pro-5g-turbo-cyan-128gb-8gb-ram-Front-Back-View_JN7AAED.webp",
                "color_variant_id": 1652,
                "color_variant_name": "Turbo Cyan",
                "storage_variant_id": 168,
                "storage_variant_name": "128 GB",
                "other_variant_id": 96,
                "other_variant_name": "8 GB",
                "stock_sataus": "In-stock",
                "id": 3319,
                "Meta_Title": "vivo T1 Pro 5G",
                "Meta_Keyword": "vivo T1 Pro 5G",
                "Meta_Description": "vivo T1 Pro 5G",
                "title": "vivo T1 Pro 5G",
                "HSN": "18999",
                "description": "vivo T1 Pro 5G",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-04-06T12:33:59.100537",
                "permission": 1,
                "slug": "vivo-t1-pro-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 192,
                "sub_category": "Vivo",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 232,
                "brand_name": "VIVO",
                "store_id": 1
            },
            {
                "quantity": "50",
                "price": 24999.0,
                "whishlist_status": "Login Required",
                "variant_id": 5279,
                "variant_name": "vivo T1 Pro 5G (Turbo Black, 128 GB)  (8 GB RAM)",
                "actual_price": 24999.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-t1-pro-5g-turbo-black-128gb-8gb-ram-Front-Back-View_XQt5E1p.webp",
                "color_variant_id": 1446,
                "color_variant_name": "Turbo Black ",
                "storage_variant_id": 168,
                "storage_variant_name": "128 GB",
                "other_variant_id": 96,
                "other_variant_name": "8 GB",
                "stock_sataus": "In-stock",
                "id": 3319,
                "Meta_Title": "vivo T1 Pro 5G",
                "Meta_Keyword": "vivo T1 Pro 5G",
                "Meta_Description": "vivo T1 Pro 5G",
                "title": "vivo T1 Pro 5G",
                "HSN": "18999",
                "description": "vivo T1 Pro 5G",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-04-06T12:33:59.100537",
                "permission": 1,
                "slug": "vivo-t1-pro-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 192,
                "sub_category": "Vivo",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 232,
                "brand_name": "VIVO",
                "store_id": 1
            },
            {
                "quantity": "2",
                "price": 16499.0,
                "whishlist_status": "Login Required",
                "variant_id": 5335,
                "variant_name": "vivo Y100 5G (Pacific Blue, 128 GB)  (8 GB RAM)",
                "actual_price": 16499.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo_Y100_qWwbZsi.jpg",
                "color_variant_id": 1475,
                "color_variant_name": "Pacific Blue",
                "storage_variant_id": 168,
                "storage_variant_name": "128 GB",
                "other_variant_id": 96,
                "other_variant_name": "8 GB",
                "stock_sataus": "In-stock",
                "id": 3344,
                "Meta_Title": "VIVO Y100 ",
                "Meta_Keyword": "VIVO Y100 ",
                "Meta_Description": "VIVO Y100 ",
                "title": "VIVO Y100 ",
                "HSN": "8517",
                "description": "The Vivo Y100 5G features colour-changing fluorite AG glass that changes colour with changes in environment and time. The 64 MP OIS anti-shake camera helps to take steady and cinematic images without any hassle. This smartphone has 8 GB RAM with an additional 8 GB of extended RAM, which allows you to keep up to 27 apps in the background. It uses a powerful MediaTek Dimensity 900 processor to give you a smooth 5G experience, and its 4500 mAh battery with 44 W FlashCharge lets the phone’s battery last for a long time This smartphone has many camera features, so you can create vlogs, movies, and click portraits as you desire. The Funtouch OS 13, allows you to have a secure OS experience, in addition to that you can also enjoy personalised settings, privacy protection, and much more.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-01-07T19:40:36.422545",
                "permission": 1,
                "slug": "vivo-y100",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 192,
                "sub_category": "Vivo",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 232,
                "brand_name": "VIVO",
                "store_id": 1
            },
            {
                "quantity": "20",
                "price": 13499.0,
                "whishlist_status": "Login Required",
                "variant_id": 5359,
                "variant_name": "SAMSUNG Galaxy A14 5G (Dark Red, 64 GB)  (4 GB RAM)",
                "actual_price": 13499.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/samsung-galaxy-a14-5g-dark-red-4gb-128gb-front-back-view-min_eDHqOU4.webp",
                "color_variant_id": 1438,
                "color_variant_name": "Dark Red ",
                "storage_variant_id": 169,
                "storage_variant_name": "64 GB",
                "other_variant_id": 97,
                "other_variant_name": "4 GB",
                "stock_sataus": "In-stock",
                "id": 3353,
                "Meta_Title": "SAMSUNG GALAXY A14 5G ",
                "Meta_Keyword": "SAMSUNG GALAXY A14 5G ",
                "Meta_Description": "SAMSUNG GALAXY A14 5G ",
                "title": "SAMSUNG Galaxy A14 5G ",
                "HSN": "85171300",
                "description": "With the feature-rich Samsung Galaxy A14 5G smartphone, you can multitask without lag and have flawless connectivity. The Galaxy A14 5G provides you with the precision and speed you need to be working with ease with its Octa-core processor and 5G connectivity. You also have a large area of view and operate on the 16.72 cm (6.6) Infinity-V Display of the Galaxy A14 5G. The 50 MP primary camera on this phone can also be used to capture beautiful landscape images. Additionally, the Dimension camera gives your photos a remarkable depth, while the Macro camera captures minute details.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-06-21T15:54:07.772549",
                "permission": 1,
                "slug": "samsung-galaxy-a14-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 185,
                "sub_category": "Samsung ",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 220,
                "brand_name": "Samsung",
                "store_id": 1
            },
            {
                "quantity": "20",
                "price": 13499.0,
                "whishlist_status": "Login Required",
                "variant_id": 5360,
                "variant_name": "SAMSUNG Galaxy A14 5G (Black, 64 GB) (4 GB RAM)",
                "actual_price": 13499.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/samsung-galaxy-a14-5g-black-128gb-4gb-ram-front-back-view-min_0VK9CxE.webp",
                "color_variant_id": 1401,
                "color_variant_name": "Black ",
                "storage_variant_id": 169,
                "storage_variant_name": "64 GB",
                "other_variant_id": 97,
                "other_variant_name": "4 GB",
                "stock_sataus": "In-stock",
                "id": 3353,
                "Meta_Title": "SAMSUNG GALAXY A14 5G ",
                "Meta_Keyword": "SAMSUNG GALAXY A14 5G ",
                "Meta_Description": "SAMSUNG GALAXY A14 5G ",
                "title": "SAMSUNG Galaxy A14 5G ",
                "HSN": "85171300",
                "description": "With the feature-rich Samsung Galaxy A14 5G smartphone, you can multitask without lag and have flawless connectivity. The Galaxy A14 5G provides you with the precision and speed you need to be working with ease with its Octa-core processor and 5G connectivity. You also have a large area of view and operate on the 16.72 cm (6.6) Infinity-V Display of the Galaxy A14 5G. The 50 MP primary camera on this phone can also be used to capture beautiful landscape images. Additionally, the Dimension camera gives your photos a remarkable depth, while the Macro camera captures minute details.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-06-21T15:54:07.772549",
                "permission": 1,
                "slug": "samsung-galaxy-a14-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 185,
                "sub_category": "Samsung ",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 220,
                "brand_name": "Samsung",
                "store_id": 1
            },
            {
                "quantity": "20",
                "price": 17999.0,
                "whishlist_status": "Login Required",
                "variant_id": 5364,
                "variant_name": "SAMSUNG Galaxy A14 5G (Black, 128 GB) (8 GB RAM)",
                "actual_price": 17999.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/samsung-galaxy-a14-5g-black-128gb-4gb-ram-front-back-view-min.webp",
                "color_variant_id": 1401,
                "color_variant_name": "Black ",
                "storage_variant_id": 168,
                "storage_variant_name": "128 GB",
                "other_variant_id": 96,
                "other_variant_name": "8 GB",
                "stock_sataus": "In-stock",
                "id": 3353,
                "Meta_Title": "SAMSUNG GALAXY A14 5G ",
                "Meta_Keyword": "SAMSUNG GALAXY A14 5G ",
                "Meta_Description": "SAMSUNG GALAXY A14 5G ",
                "title": "SAMSUNG Galaxy A14 5G ",
                "HSN": "85171300",
                "description": "With the feature-rich Samsung Galaxy A14 5G smartphone, you can multitask without lag and have flawless connectivity. The Galaxy A14 5G provides you with the precision and speed you need to be working with ease with its Octa-core processor and 5G connectivity. You also have a large area of view and operate on the 16.72 cm (6.6) Infinity-V Display of the Galaxy A14 5G. The 50 MP primary camera on this phone can also be used to capture beautiful landscape images. Additionally, the Dimension camera gives your photos a remarkable depth, while the Macro camera captures minute details.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-06-21T15:54:07.772549",
                "permission": 1,
                "slug": "samsung-galaxy-a14-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 185,
                "sub_category": "Samsung ",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 220,
                "brand_name": "Samsung",
                "store_id": 1
            },
            {
                "quantity": "50",
                "price": 27990.0,
                "whishlist_status": "Login Required",
                "variant_id": 5378,
                "variant_name": "vivo V25 5G (Surfing Blue, 128 GB)  (8 GB RAM)",
                "actual_price": 27990.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-v25-5g-surfing-blue-128gb-8gb-ram-Front-Back-View_qWNtOZh.webp",
                "color_variant_id": 1489,
                "color_variant_name": "Surfing Blue",
                "storage_variant_id": 168,
                "storage_variant_name": "128 GB",
                "other_variant_id": 96,
                "other_variant_name": "8 GB",
                "stock_sataus": "In-stock",
                "id": 3357,
                "Meta_Title": "VIVO V25 5G",
                "Meta_Keyword": "VIVO V25 5G",
                "Meta_Description": "VIVO V25 5G",
                "title": "VIVO V25 5G",
                "HSN": "85171300",
                "description": "The innovative Vivo V25 5G smartphone is designed to wow you from the inside out. It allows you to discover exciting options and capture timeless beauty. The 6 nm CPU and dual-mode 5G in this phone enable a fluid user experience. Additionally, the superb 50 MP Eye AF camera on this phone allows you to take mesmerising photos with flawless imagery. Furthermore, you can store everything you want and treasure your precious moments, thanks to an internal storage capacity of up to 256 GB and a memory expansion capability of up to 1 TB.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-04-05T19:00:35.677355",
                "permission": 1,
                "slug": "vivo-v25-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 192,
                "sub_category": "Vivo",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 232,
                "brand_name": "VIVO",
                "store_id": 1
            },
            {
                "quantity": "10",
                "price": 27999.0,
                "whishlist_status": "Login Required",
                "variant_id": 5379,
                "variant_name": "vivo V25 5G (Elegant Black, 128 GB)  (8 GB RAM)",
                "actual_price": 27999.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-v25-5g-elegant-blue-128gb-8gb-ram-Front-Back-View_2iwgxIn.webp",
                "color_variant_id": 1490,
                "color_variant_name": "Elegant Black",
                "storage_variant_id": 168,
                "storage_variant_name": "128 GB",
                "other_variant_id": 96,
                "other_variant_name": "8 GB",
                "stock_sataus": "In-stock",
                "id": 3357,
                "Meta_Title": "VIVO V25 5G",
                "Meta_Keyword": "VIVO V25 5G",
                "Meta_Description": "VIVO V25 5G",
                "title": "VIVO V25 5G",
                "HSN": "85171300",
                "description": "The innovative Vivo V25 5G smartphone is designed to wow you from the inside out. It allows you to discover exciting options and capture timeless beauty. The 6 nm CPU and dual-mode 5G in this phone enable a fluid user experience. Additionally, the superb 50 MP Eye AF camera on this phone allows you to take mesmerising photos with flawless imagery. Furthermore, you can store everything you want and treasure your precious moments, thanks to an internal storage capacity of up to 256 GB and a memory expansion capability of up to 1 TB.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-04-05T19:00:35.677355",
                "permission": 1,
                "slug": "vivo-v25-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 192,
                "sub_category": "Vivo",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 232,
                "brand_name": "VIVO",
                "store_id": 1
            },
            {
                "quantity": "10",
                "price": 31999.0,
                "whishlist_status": "Login Required",
                "variant_id": 5380,
                "variant_name": "vivo V25 5G (Surfing Blue, 256 GB)  (12 GB RAM)",
                "actual_price": 31999.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-v25-5g-surfing-blue-128gb-8gb-ram-Front-Back-View.webp",
                "color_variant_id": 1489,
                "color_variant_name": "Surfing Blue",
                "storage_variant_id": 170,
                "storage_variant_name": "256 GB",
                "other_variant_id": 100,
                "other_variant_name": "12 GB",
                "stock_sataus": "In-stock",
                "id": 3357,
                "Meta_Title": "VIVO V25 5G",
                "Meta_Keyword": "VIVO V25 5G",
                "Meta_Description": "VIVO V25 5G",
                "title": "VIVO V25 5G",
                "HSN": "85171300",
                "description": "The innovative Vivo V25 5G smartphone is designed to wow you from the inside out. It allows you to discover exciting options and capture timeless beauty. The 6 nm CPU and dual-mode 5G in this phone enable a fluid user experience. Additionally, the superb 50 MP Eye AF camera on this phone allows you to take mesmerising photos with flawless imagery. Furthermore, you can store everything you want and treasure your precious moments, thanks to an internal storage capacity of up to 256 GB and a memory expansion capability of up to 1 TB.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-04-05T19:00:35.677355",
                "permission": 1,
                "slug": "vivo-v25-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 192,
                "sub_category": "Vivo",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 232,
                "brand_name": "VIVO",
                "store_id": 1
            },
            {
                "quantity": "20",
                "price": 31999.0,
                "whishlist_status": "Login Required",
                "variant_id": 5381,
                "variant_name": "vivo V25 5G (Elegant Black, 256 GB)  (12 GB RAM)",
                "actual_price": 31999.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-v25-5g-elegant-blue-128gb-8gb-ram-Front-Back-View.webp",
                "color_variant_id": 1490,
                "color_variant_name": "Elegant Black",
                "storage_variant_id": 170,
                "storage_variant_name": "256 GB",
                "other_variant_id": 100,
                "other_variant_name": "12 GB",
                "stock_sataus": "In-stock",
                "id": 3357,
                "Meta_Title": "VIVO V25 5G",
                "Meta_Keyword": "VIVO V25 5G",
                "Meta_Description": "VIVO V25 5G",
                "title": "VIVO V25 5G",
                "HSN": "85171300",
                "description": "The innovative Vivo V25 5G smartphone is designed to wow you from the inside out. It allows you to discover exciting options and capture timeless beauty. The 6 nm CPU and dual-mode 5G in this phone enable a fluid user experience. Additionally, the superb 50 MP Eye AF camera on this phone allows you to take mesmerising photos with flawless imagery. Furthermore, you can store everything you want and treasure your precious moments, thanks to an internal storage capacity of up to 256 GB and a memory expansion capability of up to 1 TB.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-04-05T19:00:35.677355",
                "permission": 1,
                "slug": "vivo-v25-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 192,
                "sub_category": "Vivo",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 232,
                "brand_name": "VIVO",
                "store_id": 1
            },
            {
                "quantity": "50",
                "price": 39999.0,
                "whishlist_status": "Login Required",
                "variant_id": 5382,
                "variant_name": "vivo V25 Pro 5G (Sailing Blue, 256 GB)  (12 GB RAM)",
                "actual_price": 39999.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/vivo-v25-pro-sailing-blue-256gb-12gb-ram-front-back.webp",
                "color_variant_id": 1491,
                "color_variant_name": "Sailing Blue",
                "storage_variant_id": 170,
                "storage_variant_name": "256 GB",
                "other_variant_id": 100,
                "other_variant_name": "12 GB",
                "stock_sataus": "In-stock",
                "id": 3358,
                "Meta_Title": "VIVO V25 PRO 5G",
                "Meta_Keyword": "VIVO V25 PRO 5G",
                "Meta_Description": "VIVO V25 PRO 5G",
                "title": "VIVO V25 PRO 5G",
                "HSN": "85171300",
                "description": "With the innovative Vivo V25 Pro 5G smartphone, which is perfectly suited for multitaskers, you can effortlessly elevate your entertainment to a different extreme and enhance your productivity. This phone boosts your performance with its magnificent 16.66 cm (6.56) POLED display and quick 120 Hz refresh rate. Furthermore, you can take mesmerising pictures with outstanding graphics thanks to a fantastic back camera arrangement and a 32 MP front camera. Additionally, this phone meets all of your multitasking demands owing to its MediaTek Dimensity 1300 processor and 6 nm architecture.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-04-10T20:10:13.501446",
                "permission": 1,
                "slug": "vivo-v25-pro-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 192,
                "sub_category": "Vivo",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 232,
                "brand_name": "VIVO",
                "store_id": 1
            },
            {
                "quantity": "20",
                "price": 35999.0,
                "whishlist_status": "Login Required",
                "variant_id": 5383,
                "variant_name": "vivo V25 Pro 5G (Pure Black, 128 GB)  (8 GB RAM)",
                "actual_price": 35999.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-v25-pro-pure-black-256gb-12gb-ram-Front-Back-Side-View_Rak7qq9.webp",
                "color_variant_id": 1492,
                "color_variant_name": "Pure Black",
                "storage_variant_id": 168,
                "storage_variant_name": "128 GB",
                "other_variant_id": 96,
                "other_variant_name": "8 GB",
                "stock_sataus": "In-stock",
                "id": 3358,
                "Meta_Title": "VIVO V25 PRO 5G",
                "Meta_Keyword": "VIVO V25 PRO 5G",
                "Meta_Description": "VIVO V25 PRO 5G",
                "title": "VIVO V25 PRO 5G",
                "HSN": "85171300",
                "description": "With the innovative Vivo V25 Pro 5G smartphone, which is perfectly suited for multitaskers, you can effortlessly elevate your entertainment to a different extreme and enhance your productivity. This phone boosts your performance with its magnificent 16.66 cm (6.56) POLED display and quick 120 Hz refresh rate. Furthermore, you can take mesmerising pictures with outstanding graphics thanks to a fantastic back camera arrangement and a 32 MP front camera. Additionally, this phone meets all of your multitasking demands owing to its MediaTek Dimensity 1300 processor and 6 nm architecture.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-04-10T20:10:13.501446",
                "permission": 1,
                "slug": "vivo-v25-pro-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 192,
                "sub_category": "Vivo",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 232,
                "brand_name": "VIVO",
                "store_id": 1
            },
            {
                "quantity": "2",
                "price": 35999.0,
                "whishlist_status": "Login Required",
                "variant_id": 5384,
                "variant_name": "vivo V25 Pro 5G (Pure Black, 256 GB)  (12 GB RAM)",
                "actual_price": 35999.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-v25-pro-pure-black-256gb-12gb-ram-Front-Back-Side-View.webp",
                "color_variant_id": 1492,
                "color_variant_name": "Pure Black",
                "storage_variant_id": 170,
                "storage_variant_name": "256 GB",
                "other_variant_id": 100,
                "other_variant_name": "12 GB",
                "stock_sataus": "In-stock",
                "id": 3358,
                "Meta_Title": "VIVO V25 PRO 5G",
                "Meta_Keyword": "VIVO V25 PRO 5G",
                "Meta_Description": "VIVO V25 PRO 5G",
                "title": "VIVO V25 PRO 5G",
                "HSN": "85171300",
                "description": "With the innovative Vivo V25 Pro 5G smartphone, which is perfectly suited for multitaskers, you can effortlessly elevate your entertainment to a different extreme and enhance your productivity. This phone boosts your performance with its magnificent 16.66 cm (6.56) POLED display and quick 120 Hz refresh rate. Furthermore, you can take mesmerising pictures with outstanding graphics thanks to a fantastic back camera arrangement and a 32 MP front camera. Additionally, this phone meets all of your multitasking demands owing to its MediaTek Dimensity 1300 processor and 6 nm architecture.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-04-10T20:10:13.501446",
                "permission": 1,
                "slug": "vivo-v25-pro-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 192,
                "sub_category": "Vivo",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 232,
                "brand_name": "VIVO",
                "store_id": 1
            },
            {
                "quantity": "10",
                "price": 46400.0,
                "whishlist_status": "Login Required",
                "variant_id": 5386,
                "variant_name": "APPLE iPhone 13 (Blue, 128 GB)",
                "actual_price": 46400.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Apple-iPhone-13-Smartphones-blue.jpg",
                "color_variant_id": 1409,
                "color_variant_name": "Blue",
                "storage_variant_id": 168,
                "storage_variant_name": "128 GB",
                "other_variant_id": "",
                "other_variant_name": "",
                "stock_sataus": "In-stock",
                "id": 3360,
                "Meta_Title": "Apple iPhone 13",
                "Meta_Keyword": "Apple iPhone 13",
                "Meta_Description": "Apple iPhone 13",
                "title": "Apple iPhone 13",
                "HSN": "85171300",
                "description": "<p>The iPhone 13 features a stylish design and innovative features that make it a delight to use. It is equipped with a Dual-camera system that adds an upgrade to the photos and videos that you take. It offers a big boost in battery so that you have enough time to watch content, game, and so on. And, the A15 Bionic helps load graphics-intensive games with ease.&nbsp;</p>",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2025-01-22T22:50:33.647504",
                "permission": 1,
                "slug": "apple-iphone-13",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 194,
                "sub_category": "Apple",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 260,
                "brand_name": "Apple",
                "store_id": 1
            },
            {
                "quantity": "10",
                "price": 46400.0,
                "whishlist_status": "Login Required",
                "variant_id": 5388,
                "variant_name": "APPLE iPhone 13 (Green, 128 GB)",
                "actual_price": 46400.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Apple-iPhone-13-Smartphones-GREEN.jpg",
                "color_variant_id": 1494,
                "color_variant_name": "Green",
                "storage_variant_id": 168,
                "storage_variant_name": "128 GB",
                "other_variant_id": "",
                "other_variant_name": "",
                "stock_sataus": "In-stock",
                "id": 3360,
                "Meta_Title": "Apple iPhone 13",
                "Meta_Keyword": "Apple iPhone 13",
                "Meta_Description": "Apple iPhone 13",
                "title": "Apple iPhone 13",
                "HSN": "85171300",
                "description": "<p>The iPhone 13 features a stylish design and innovative features that make it a delight to use. It is equipped with a Dual-camera system that adds an upgrade to the photos and videos that you take. It offers a big boost in battery so that you have enough time to watch content, game, and so on. And, the A15 Bionic helps load graphics-intensive games with ease.&nbsp;</p>",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2025-01-22T22:50:33.647504",
                "permission": 1,
                "slug": "apple-iphone-13",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 194,
                "sub_category": "Apple",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 260,
                "brand_name": "Apple",
                "store_id": 1
            },
            {
                "quantity": "10",
                "price": 46400.0,
                "whishlist_status": "Login Required",
                "variant_id": 5389,
                "variant_name": "APPLE iPhone 13 (Pink, 128 GB)",
                "actual_price": 46400.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Apple-MLPH3HN-A-SmartPhones-PINK.jpg",
                "color_variant_id": 1495,
                "color_variant_name": "Pink",
                "storage_variant_id": 168,
                "storage_variant_name": "128 GB",
                "other_variant_id": "",
                "other_variant_name": "",
                "stock_sataus": "In-stock",
                "id": 3360,
                "Meta_Title": "Apple iPhone 13",
                "Meta_Keyword": "Apple iPhone 13",
                "Meta_Description": "Apple iPhone 13",
                "title": "Apple iPhone 13",
                "HSN": "85171300",
                "description": "<p>The iPhone 13 features a stylish design and innovative features that make it a delight to use. It is equipped with a Dual-camera system that adds an upgrade to the photos and videos that you take. It offers a big boost in battery so that you have enough time to watch content, game, and so on. And, the A15 Bionic helps load graphics-intensive games with ease.&nbsp;</p>",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2025-01-22T22:50:33.647504",
                "permission": 1,
                "slug": "apple-iphone-13",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 194,
                "sub_category": "Apple",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 260,
                "brand_name": "Apple",
                "store_id": 1
            },
            {
                "quantity": "10",
                "price": 46400.0,
                "whishlist_status": "Login Required",
                "variant_id": 5390,
                "variant_name": "APPLE iPhone 13 (Starlight, 128 GB)",
                "actual_price": 46400.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Apple-MLPG3HN-A-SmartPhones-Starlight.jpg",
                "color_variant_id": 1496,
                "color_variant_name": "Starlight",
                "storage_variant_id": 168,
                "storage_variant_name": "128 GB",
                "other_variant_id": "",
                "other_variant_name": "",
                "stock_sataus": "In-stock",
                "id": 3360,
                "Meta_Title": "Apple iPhone 13",
                "Meta_Keyword": "Apple iPhone 13",
                "Meta_Description": "Apple iPhone 13",
                "title": "Apple iPhone 13",
                "HSN": "85171300",
                "description": "<p>The iPhone 13 features a stylish design and innovative features that make it a delight to use. It is equipped with a Dual-camera system that adds an upgrade to the photos and videos that you take. It offers a big boost in battery so that you have enough time to watch content, game, and so on. And, the A15 Bionic helps load graphics-intensive games with ease.&nbsp;</p>",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2025-01-22T22:50:33.647504",
                "permission": 1,
                "slug": "apple-iphone-13",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 194,
                "sub_category": "Apple",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 260,
                "brand_name": "Apple",
                "store_id": 1
            },
            {
                "quantity": "10",
                "price": 46400.0,
                "whishlist_status": "Login Required",
                "variant_id": 5391,
                "variant_name": "Apple iPhone 13 (Midnight, 128 GB)",
                "actual_price": 46400.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Apple-MLPF3HN-A-Smart-Phone-Midnight_Black.jpg",
                "color_variant_id": 1497,
                "color_variant_name": "Midnight",
                "storage_variant_id": 168,
                "storage_variant_name": "128 GB",
                "other_variant_id": "",
                "other_variant_name": "",
                "stock_sataus": "In-stock",
                "id": 3360,
                "Meta_Title": "Apple iPhone 13",
                "Meta_Keyword": "Apple iPhone 13",
                "Meta_Description": "Apple iPhone 13",
                "title": "Apple iPhone 13",
                "HSN": "85171300",
                "description": "<p>The iPhone 13 features a stylish design and innovative features that make it a delight to use. It is equipped with a Dual-camera system that adds an upgrade to the photos and videos that you take. It offers a big boost in battery so that you have enough time to watch content, game, and so on. And, the A15 Bionic helps load graphics-intensive games with ease.&nbsp;</p>",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2025-01-22T22:50:33.647504",
                "permission": 1,
                "slug": "apple-iphone-13",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 194,
                "sub_category": "Apple",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 260,
                "brand_name": "Apple",
                "store_id": 1
            },
            {
                "quantity": "100",
                "price": 10990.0,
                "whishlist_status": "Login Required",
                "variant_id": 5492,
                "variant_name": "Tecno Pova Neo (Sprint Blue , 128GB+6GB)",
                "actual_price": 10990.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/New_crazzyhub_2_10_OEvD2V0.jpg",
                "color_variant_id": 1513,
                "color_variant_name": "Sprint Blue ",
                "storage_variant_id": 168,
                "storage_variant_name": "128 GB",
                "other_variant_id": 98,
                "other_variant_name": "6 GB",
                "stock_sataus": "In-stock",
                "id": 3386,
                "Meta_Title": "Tecno Pova Neo",
                "Meta_Keyword": "Tecno Pova Neo",
                "Meta_Description": "Tecno Pova Neo",
                "title": "Tecno Pova Neo",
                "HSN": "8517",
                "description": "Tecno Pova Neo is a compact performer incorporated with a wide range of brilliant specs under the hood. It is all set to offer a fulfilling experience regarding gaming, photography and the operational needs of individual users.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2023-07-18T20:07:52.440701",
                "permission": 1,
                "slug": "tecno-pova-neo",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 179,
                "sub_category": "Tecno",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 224,
                "brand_name": "Tecno",
                "store_id": 1
            },
            {
                "quantity": "10",
                "price": 15690.0,
                "whishlist_status": "Login Required",
                "variant_id": 5495,
                "variant_name": "Tecno Pova Neo 5G (Greek Blue, 128GB) (6GB RAM)",
                "actual_price": 15690.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/71H2SdmX26L_1wPpqrs.jpg",
                "color_variant_id": 1515,
                "color_variant_name": "Geek Blue",
                "storage_variant_id": 168,
                "storage_variant_name": "128 GB",
                "other_variant_id": 98,
                "other_variant_name": "6 GB",
                "stock_sataus": "In-stock",
                "id": 3389,
                "Meta_Title": "Tecno Pova Neo (5G)",
                "Meta_Keyword": "Tecno Pova Neo (5G)",
                "Meta_Description": "Tecno Pova Neo (5G)",
                "title": "Tecno Pova Neo (5G)",
                "HSN": "8517",
                "description": "The Tecno Pova Neo 5G is a pretty decent device that comes with a set of specifications that will help you to carry out your day-to-day tasks comfortably. Tecno has offered a massive 6000mAh battery so that you can run it for prolonged hours. A 6.8-inches IPS LCD comes on the front side of the Tecno Pova Neo 5G and it offers a resolution of 2460 x 1080 pixels and a pixel density of 395ppi. The refresh rate of this display is 120Hz and it is built with an aspect ratio of 20:9. There is only a single 50MP camera available on the back surface of the Tecno Pova Neo 5G. This camera has an f/1.6 aperture and it comes with a Quad-LED Flash. Tecno has also installed an 8MP resolution camera on the front side. This front camera has an aperture of f/2.0 and it also comes with a Dual LED Flash. The Tecno Pova Neo 5G ensures consistent and quick performance with the help of its MediaTek Dimensity 810 MT6833 chipset, 4GB LPDDR4X RAM and an Eight-core processor featuring a layout of Cortex A76 and Cortex A55. Moreover, a Mali-G57 MC2 GPU is also present inside this smartphone. The 6000mAh Li-Polymer battery of the Tecno Pova Neo 5G promises to run it for an entire day. To charge this battery, a Flash Charging mechanism of 18W is also available in it.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-04-26T19:59:03.894469",
                "permission": 1,
                "slug": "tecno-pova-neo-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 179,
                "sub_category": "Tecno",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 224,
                "brand_name": "Tecno",
                "store_id": 1
            },
            {
                "quantity": "10",
                "price": 15499.0,
                "whishlist_status": "Login Required",
                "variant_id": 5496,
                "variant_name": "Tecno Pova Neo 5G (Sapphire Black, 128 GB)  (4 GB RAM)",
                "actual_price": 15499.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/tecno-pova-neo-5g-sapphire-black-128-gb-4-gb-ram--1000x1000_y4lkmjH.webp",
                "color_variant_id": "",
                "color_variant_name": "",
                "storage_variant_id": 168,
                "storage_variant_name": "128 GB",
                "other_variant_id": 97,
                "other_variant_name": "4 GB",
                "stock_sataus": "In-stock",
                "id": 3389,
                "Meta_Title": "Tecno Pova Neo (5G)",
                "Meta_Keyword": "Tecno Pova Neo (5G)",
                "Meta_Description": "Tecno Pova Neo (5G)",
                "title": "Tecno Pova Neo (5G)",
                "HSN": "8517",
                "description": "The Tecno Pova Neo 5G is a pretty decent device that comes with a set of specifications that will help you to carry out your day-to-day tasks comfortably. Tecno has offered a massive 6000mAh battery so that you can run it for prolonged hours. A 6.8-inches IPS LCD comes on the front side of the Tecno Pova Neo 5G and it offers a resolution of 2460 x 1080 pixels and a pixel density of 395ppi. The refresh rate of this display is 120Hz and it is built with an aspect ratio of 20:9. There is only a single 50MP camera available on the back surface of the Tecno Pova Neo 5G. This camera has an f/1.6 aperture and it comes with a Quad-LED Flash. Tecno has also installed an 8MP resolution camera on the front side. This front camera has an aperture of f/2.0 and it also comes with a Dual LED Flash. The Tecno Pova Neo 5G ensures consistent and quick performance with the help of its MediaTek Dimensity 810 MT6833 chipset, 4GB LPDDR4X RAM and an Eight-core processor featuring a layout of Cortex A76 and Cortex A55. Moreover, a Mali-G57 MC2 GPU is also present inside this smartphone. The 6000mAh Li-Polymer battery of the Tecno Pova Neo 5G promises to run it for an entire day. To charge this battery, a Flash Charging mechanism of 18W is also available in it.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-04-26T19:59:03.894469",
                "permission": 1,
                "slug": "tecno-pova-neo-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 179,
                "sub_category": "Tecno",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 224,
                "brand_name": "Tecno",
                "store_id": 1
            },
            {
                "quantity": "10",
                "price": 15499.0,
                "whishlist_status": "Login Required",
                "variant_id": 5497,
                "variant_name": "Tecno Pova Neo 5G (Sprint Blue, 128 GB)  (4 GB RAM)",
                "actual_price": 15499.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/tecno-pova-neo-5g-sprint-blue-128-gb-4-gb-ram--1000x1000.webp",
                "color_variant_id": 1513,
                "color_variant_name": "Sprint Blue ",
                "storage_variant_id": 168,
                "storage_variant_name": "128 GB",
                "other_variant_id": 97,
                "other_variant_name": "4 GB",
                "stock_sataus": "In-stock",
                "id": 3389,
                "Meta_Title": "Tecno Pova Neo (5G)",
                "Meta_Keyword": "Tecno Pova Neo (5G)",
                "Meta_Description": "Tecno Pova Neo (5G)",
                "title": "Tecno Pova Neo (5G)",
                "HSN": "8517",
                "description": "The Tecno Pova Neo 5G is a pretty decent device that comes with a set of specifications that will help you to carry out your day-to-day tasks comfortably. Tecno has offered a massive 6000mAh battery so that you can run it for prolonged hours. A 6.8-inches IPS LCD comes on the front side of the Tecno Pova Neo 5G and it offers a resolution of 2460 x 1080 pixels and a pixel density of 395ppi. The refresh rate of this display is 120Hz and it is built with an aspect ratio of 20:9. There is only a single 50MP camera available on the back surface of the Tecno Pova Neo 5G. This camera has an f/1.6 aperture and it comes with a Quad-LED Flash. Tecno has also installed an 8MP resolution camera on the front side. This front camera has an aperture of f/2.0 and it also comes with a Dual LED Flash. The Tecno Pova Neo 5G ensures consistent and quick performance with the help of its MediaTek Dimensity 810 MT6833 chipset, 4GB LPDDR4X RAM and an Eight-core processor featuring a layout of Cortex A76 and Cortex A55. Moreover, a Mali-G57 MC2 GPU is also present inside this smartphone. The 6000mAh Li-Polymer battery of the Tecno Pova Neo 5G promises to run it for an entire day. To charge this battery, a Flash Charging mechanism of 18W is also available in it.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-04-26T19:59:03.894469",
                "permission": 1,
                "slug": "tecno-pova-neo-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 179,
                "sub_category": "Tecno",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 224,
                "brand_name": "Tecno",
                "store_id": 1
            },
            {
                "quantity": "2",
                "price": 22999.0,
                "whishlist_status": "Login Required",
                "variant_id": 5510,
                "variant_name": "vivo Y100A 5G (Pacific Blue, 256 GB) (8 GB RAM)",
                "actual_price": 22999.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-y100a-5g-pacific-blue-128gb-8gb-ram-Front-Back-View_h90IGA5.webp",
                "color_variant_id": 1475,
                "color_variant_name": "Pacific Blue",
                "storage_variant_id": 170,
                "storage_variant_name": "256 GB",
                "other_variant_id": 96,
                "other_variant_name": "8 GB",
                "stock_sataus": "In-stock",
                "id": 3395,
                "Meta_Title": "",
                "Meta_Keyword": "",
                "Meta_Description": "",
                "title": "VIVO Y100A 5G",
                "HSN": "85171300",
                "description": "Y100A",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-04-08T19:13:07.772340",
                "permission": 1,
                "slug": "vivo-y100a-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 192,
                "sub_category": "Vivo",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 232,
                "brand_name": "VIVO",
                "store_id": 1
            },
            {
                "quantity": "2",
                "price": 22999.0,
                "whishlist_status": "Login Required",
                "variant_id": 5511,
                "variant_name": "vivo Y100A 5G (Twilight Gold, 256 GB) (8 GB RAM)",
                "actual_price": 22999.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/vivo-y100a-5g-twilight-gold-8gb-128gb-Front-Back-View_AjoiBRY.webp",
                "color_variant_id": 1477,
                "color_variant_name": "Twilight Gold",
                "storage_variant_id": 170,
                "storage_variant_name": "256 GB",
                "other_variant_id": 96,
                "other_variant_name": "8 GB",
                "stock_sataus": "In-stock",
                "id": 3395,
                "Meta_Title": "",
                "Meta_Keyword": "",
                "Meta_Description": "",
                "title": "VIVO Y100A 5G",
                "HSN": "85171300",
                "description": "Y100A",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-04-08T19:13:07.772340",
                "permission": 1,
                "slug": "vivo-y100a-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 192,
                "sub_category": "Vivo",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 232,
                "brand_name": "VIVO",
                "store_id": 1
            },
            {
                "quantity": "25",
                "price": 59999.0,
                "whishlist_status": "Login Required",
                "variant_id": 5512,
                "variant_name": "vivo X90 (Breeze Blue, 256 GB) (8 GB RAM)",
                "actual_price": 59999.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-x90-5g-breeze-blue-256gb-12gb-ram-Front-Back-View_dyKvI71.webp",
                "color_variant_id": 1519,
                "color_variant_name": "Breeze Blue",
                "storage_variant_id": 170,
                "storage_variant_name": "256 GB",
                "other_variant_id": 96,
                "other_variant_name": "8 GB",
                "stock_sataus": "In-stock",
                "id": 3396,
                "Meta_Title": "",
                "Meta_Keyword": "",
                "Meta_Description": "",
                "title": "VIVO X90 5G",
                "HSN": "85171300",
                "description": "With the Vivo X90 smartphone, you can experience the beauty of natural colours on its 50 MP VCS True Colour camera. If you love capturing the night life, this phone is the perfect option for you as its Xtreme Night Video algorithm is truly mesmerising. With the ZEISS Style Portrait, you can capture stunning portraits during the day or at night. The ZEISS Cine-flare Portrait allows you to take movie-like portraits. The Vivo V2 chip featured in this smartphone enhances the imaging and performance capabilities of this phone. The 120 W FlashCharge ensures long-lasting battery life to your phone. This smartphone uses a MediaTek Dimensity 9200 processor for fast and smooth processing. It has a stunning design and is also scratch and drop resistant, making it suitable for all your adventures.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-06-21T13:09:15.764623",
                "permission": 1,
                "slug": "vivo-x90-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 192,
                "sub_category": "Vivo",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 232,
                "brand_name": "VIVO",
                "store_id": 1
            },
            {
                "quantity": "25",
                "price": 59999.0,
                "whishlist_status": "Login Required",
                "variant_id": 5513,
                "variant_name": "vivo X90 (Asteroid Black, 256 GB) (8 GB RAM)",
                "actual_price": 59999.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-x90-5g-asteriod-black-256gb-12gb-ram-Front-Back-View_aUex1ub.webp",
                "color_variant_id": 1520,
                "color_variant_name": "Asteroid Black",
                "storage_variant_id": 170,
                "storage_variant_name": "256 GB",
                "other_variant_id": 96,
                "other_variant_name": "8 GB",
                "stock_sataus": "In-stock",
                "id": 3396,
                "Meta_Title": "",
                "Meta_Keyword": "",
                "Meta_Description": "",
                "title": "VIVO X90 5G",
                "HSN": "85171300",
                "description": "With the Vivo X90 smartphone, you can experience the beauty of natural colours on its 50 MP VCS True Colour camera. If you love capturing the night life, this phone is the perfect option for you as its Xtreme Night Video algorithm is truly mesmerising. With the ZEISS Style Portrait, you can capture stunning portraits during the day or at night. The ZEISS Cine-flare Portrait allows you to take movie-like portraits. The Vivo V2 chip featured in this smartphone enhances the imaging and performance capabilities of this phone. The 120 W FlashCharge ensures long-lasting battery life to your phone. This smartphone uses a MediaTek Dimensity 9200 processor for fast and smooth processing. It has a stunning design and is also scratch and drop resistant, making it suitable for all your adventures.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-06-21T13:09:15.764623",
                "permission": 1,
                "slug": "vivo-x90-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 192,
                "sub_category": "Vivo",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 232,
                "brand_name": "VIVO",
                "store_id": 1
            },
            {
                "quantity": "25",
                "price": 63999.0,
                "whishlist_status": "Login Required",
                "variant_id": 5514,
                "variant_name": "vivo X90 (Breeze Blue, 256 GB) (12 GB RAM)",
                "actual_price": 63999.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-x90-5g-breeze-blue-256gb-12gb-ram-Front-Back-View.webp",
                "color_variant_id": 1519,
                "color_variant_name": "Breeze Blue",
                "storage_variant_id": 170,
                "storage_variant_name": "256 GB",
                "other_variant_id": 100,
                "other_variant_name": "12 GB",
                "stock_sataus": "In-stock",
                "id": 3396,
                "Meta_Title": "",
                "Meta_Keyword": "",
                "Meta_Description": "",
                "title": "VIVO X90 5G",
                "HSN": "85171300",
                "description": "With the Vivo X90 smartphone, you can experience the beauty of natural colours on its 50 MP VCS True Colour camera. If you love capturing the night life, this phone is the perfect option for you as its Xtreme Night Video algorithm is truly mesmerising. With the ZEISS Style Portrait, you can capture stunning portraits during the day or at night. The ZEISS Cine-flare Portrait allows you to take movie-like portraits. The Vivo V2 chip featured in this smartphone enhances the imaging and performance capabilities of this phone. The 120 W FlashCharge ensures long-lasting battery life to your phone. This smartphone uses a MediaTek Dimensity 9200 processor for fast and smooth processing. It has a stunning design and is also scratch and drop resistant, making it suitable for all your adventures.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-06-21T13:09:15.764623",
                "permission": 1,
                "slug": "vivo-x90-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 192,
                "sub_category": "Vivo",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 232,
                "brand_name": "VIVO",
                "store_id": 1
            },
            {
                "quantity": "25",
                "price": 63999.0,
                "whishlist_status": "Login Required",
                "variant_id": 5515,
                "variant_name": "vivo X90 (Asteroid Black, 256 GB) (12 GB RAM)",
                "actual_price": 63999.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-x90-5g-asteriod-black-256gb-12gb-ram-Front-Back-View.webp",
                "color_variant_id": 1520,
                "color_variant_name": "Asteroid Black",
                "storage_variant_id": 170,
                "storage_variant_name": "256 GB",
                "other_variant_id": 100,
                "other_variant_name": "12 GB",
                "stock_sataus": "In-stock",
                "id": 3396,
                "Meta_Title": "",
                "Meta_Keyword": "",
                "Meta_Description": "",
                "title": "VIVO X90 5G",
                "HSN": "85171300",
                "description": "With the Vivo X90 smartphone, you can experience the beauty of natural colours on its 50 MP VCS True Colour camera. If you love capturing the night life, this phone is the perfect option for you as its Xtreme Night Video algorithm is truly mesmerising. With the ZEISS Style Portrait, you can capture stunning portraits during the day or at night. The ZEISS Cine-flare Portrait allows you to take movie-like portraits. The Vivo V2 chip featured in this smartphone enhances the imaging and performance capabilities of this phone. The 120 W FlashCharge ensures long-lasting battery life to your phone. This smartphone uses a MediaTek Dimensity 9200 processor for fast and smooth processing. It has a stunning design and is also scratch and drop resistant, making it suitable for all your adventures.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-06-21T13:09:15.764623",
                "permission": 1,
                "slug": "vivo-x90-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 192,
                "sub_category": "Vivo",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 232,
                "brand_name": "VIVO",
                "store_id": 1
            },
            {
                "quantity": "25",
                "price": 74999.0,
                "whishlist_status": "Login Required",
                "variant_id": 5516,
                "variant_name": "vivo X90 Pro (Legendary Black, 256 GB) (12 GB RAM)",
                "actual_price": 74999.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/vivo-x90-pro-5g-legendary-black-256gb-12gb-ram-Front-Back-View.webp",
                "color_variant_id": 1521,
                "color_variant_name": "Legendary Black",
                "storage_variant_id": 170,
                "storage_variant_name": "256 GB",
                "other_variant_id": 100,
                "other_variant_name": "12 GB",
                "stock_sataus": "In-stock",
                "id": 3397,
                "Meta_Title": "",
                "Meta_Keyword": "",
                "Meta_Description": "",
                "title": "VIVO X90 PRO 5G",
                "HSN": "85171300",
                "description": "If you are looking for a smartphone to capture mesmerising photos, then Vivo X90 Pro is the perfect choice for you. The 2.54 cm (1) large IMX989 sensor improves the light sensitivity to make your photos more attractive even in low-light conditions. This smartphone has an Xtreme Night Video algorithm that allows you to capture nightlife in its true form. It has a 50 MP portrait lens with IMX758 sensor that improves the resolution of every image you click. The Vivo V2 chip works together with this phone’s main chip to enhance its performance and imaging capabilities. It is supported by a 120 W FlashCharge to ensure long-lasting battery life so you can go all day long filming. It uses a MediaTek Dimensity 9200 processor for fast and smooth processing on this smartphone.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-06-21T13:11:34.316914",
                "permission": 1,
                "slug": "vivo-x90-pro-5g",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 192,
                "sub_category": "Vivo",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 232,
                "brand_name": "VIVO",
                "store_id": 1
            },
            {
                "quantity": "25",
                "price": 8999.0,
                "whishlist_status": "Login Required",
                "variant_id": 5537,
                "variant_name": "SAMSUNG Galaxy A04e (Copper, 64 GB)  (3 GB RAM)",
                "actual_price": 8999.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Samsung-galaxy-a04e-copper-32gb-3gb-ram-Front-back-View_h3tYIT1.webp",
                "color_variant_id": 1526,
                "color_variant_name": "Copper",
                "storage_variant_id": 169,
                "storage_variant_name": "64 GB",
                "other_variant_id": 99,
                "other_variant_name": "3 GB",
                "stock_sataus": "In-stock",
                "id": 3401,
                "Meta_Title": "",
                "Meta_Keyword": "",
                "Meta_Description": "",
                "title": "SAMSUNG Galaxy A04e",
                "HSN": "85171300",
                "description": "Galaxy A04e comes with a large battery of 5000mAh with adaptive fast charging, multi role dual camera, 13MP main, 2MP macro camera and a big display for big fun with 6.5\" big screen, copper, light blue colours with haze and matt effect makes you have unique and vivid style.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-06-21T15:25:50.697700",
                "permission": 1,
                "slug": "samsung-galaxy-a04e",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 185,
                "sub_category": "Samsung ",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 220,
                "brand_name": "Samsung",
                "store_id": 1
            },
            {
                "quantity": "25",
                "price": 8999.0,
                "whishlist_status": "Login Required",
                "variant_id": 5538,
                "variant_name": "SAMSUNG Galaxy A04e (Light Blue, 64 GB)  (3 GB RAM)",
                "actual_price": 8999.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Samsung-galaxy-a04e-light-blue-32gb-3gb-ram-Front-Back-View_S5IpulV.webp",
                "color_variant_id": 1485,
                "color_variant_name": "Light Blue",
                "storage_variant_id": 169,
                "storage_variant_name": "64 GB",
                "other_variant_id": 99,
                "other_variant_name": "3 GB",
                "stock_sataus": "In-stock",
                "id": 3401,
                "Meta_Title": "",
                "Meta_Keyword": "",
                "Meta_Description": "",
                "title": "SAMSUNG Galaxy A04e",
                "HSN": "85171300",
                "description": "Galaxy A04e comes with a large battery of 5000mAh with adaptive fast charging, multi role dual camera, 13MP main, 2MP macro camera and a big display for big fun with 6.5\" big screen, copper, light blue colours with haze and matt effect makes you have unique and vivid style.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-06-21T15:25:50.697700",
                "permission": 1,
                "slug": "samsung-galaxy-a04e",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 185,
                "sub_category": "Samsung ",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 220,
                "brand_name": "Samsung",
                "store_id": 1
            },
            {
                "quantity": "25",
                "price": 10499.0,
                "whishlist_status": "Login Required",
                "variant_id": 5539,
                "variant_name": "SAMSUNG Galaxy A04e (Copper, 128 GB)  (4 GB RAM)",
                "actual_price": 10499.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Samsung-galaxy-a04e-copper-32gb-3gb-ram-Front-back-View.webp",
                "color_variant_id": 1526,
                "color_variant_name": "Copper",
                "storage_variant_id": 168,
                "storage_variant_name": "128 GB",
                "other_variant_id": 97,
                "other_variant_name": "4 GB",
                "stock_sataus": "In-stock",
                "id": 3401,
                "Meta_Title": "",
                "Meta_Keyword": "",
                "Meta_Description": "",
                "title": "SAMSUNG Galaxy A04e",
                "HSN": "85171300",
                "description": "Galaxy A04e comes with a large battery of 5000mAh with adaptive fast charging, multi role dual camera, 13MP main, 2MP macro camera and a big display for big fun with 6.5\" big screen, copper, light blue colours with haze and matt effect makes you have unique and vivid style.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-06-21T15:25:50.697700",
                "permission": 1,
                "slug": "samsung-galaxy-a04e",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 185,
                "sub_category": "Samsung ",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 220,
                "brand_name": "Samsung",
                "store_id": 1
            },
            {
                "quantity": "25",
                "price": 10499.0,
                "whishlist_status": "Login Required",
                "variant_id": 5540,
                "variant_name": "SAMSUNG Galaxy A04e (Light Blue, 128 GB)  (4 GB RAM)",
                "actual_price": 10499.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Samsung-galaxy-a04e-light-blue-32gb-3gb-ram-Front-Back-View.webp",
                "color_variant_id": 1485,
                "color_variant_name": "Light Blue",
                "storage_variant_id": 168,
                "storage_variant_name": "128 GB",
                "other_variant_id": 97,
                "other_variant_name": "4 GB",
                "stock_sataus": "In-stock",
                "id": 3401,
                "Meta_Title": "",
                "Meta_Keyword": "",
                "Meta_Description": "",
                "title": "SAMSUNG Galaxy A04e",
                "HSN": "85171300",
                "description": "Galaxy A04e comes with a large battery of 5000mAh with adaptive fast charging, multi role dual camera, 13MP main, 2MP macro camera and a big display for big fun with 6.5\" big screen, copper, light blue colours with haze and matt effect makes you have unique and vivid style.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-06-21T15:25:50.697700",
                "permission": 1,
                "slug": "samsung-galaxy-a04e",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 185,
                "sub_category": "Samsung ",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 220,
                "brand_name": "Samsung",
                "store_id": 1
            },
            {
                "quantity": "20",
                "price": 8299.0,
                "whishlist_status": "Login Required",
                "variant_id": 5575,
                "variant_name": "REDMI 12C (Mint Green, 64 GB)  (4 GB RAM)",
                "actual_price": 8299.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Redmi-12C-Mint-green-4GB-128GB-front-and-back-view_q5Ul53C.webp",
                "color_variant_id": 1538,
                "color_variant_name": "Mint Green",
                "storage_variant_id": 169,
                "storage_variant_name": "64 GB",
                "other_variant_id": 97,
                "other_variant_name": "4 GB",
                "stock_sataus": "In-stock",
                "id": 3409,
                "Meta_Title": "",
                "Meta_Keyword": "",
                "Meta_Description": "",
                "title": "Redmi 12C",
                "HSN": "85171300",
                "description": "Redmi 12C",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2024-07-15T01:57:20.342049",
                "permission": 1,
                "slug": "redmi-12c",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 193,
                "sub_category": "Redmi",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 222,
                "brand_name": "Redmi",
                "store_id": 1
            },
            {
                "quantity": "10",
                "price": 1449.0,
                "whishlist_status": "Login Required",
                "variant_id": 5612,
                "variant_name": "Nokia 105 Dual Sim  (Blue)",
                "actual_price": 1449.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/nokia_105_blue.jpg",
                "color_variant_id": 1409,
                "color_variant_name": "Blue",
                "storage_variant_id": "",
                "storage_variant_name": "",
                "other_variant_id": "",
                "other_variant_name": "",
                "stock_sataus": "In-stock",
                "id": 3414,
                "Meta_Title": "meta_tag_title",
                "Meta_Keyword": "meta_tag_keywords\n",
                "Meta_Description": "meta_tag_description",
                "title": "Nokia 105 TA-1459 DS",
                "HSN": "85171400",
                "description": "The Nokia 105 DS feature phone will take you on a trip down memory lane, where your phone was used for basic communication purposes and the occasional game of Snake. This phone is ergonomically designed with an Island Keymat that lets you type and dial easily. It also offers up to 15 hours of talk time to let you have endless conversations with your dear one.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2023-10-27T17:36:36.269816",
                "permission": 1,
                "slug": "nokia-105-ta-1459-ds",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 191,
                "sub_category": "Nokia",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 231,
                "brand_name": "Nokia",
                "store_id": 1
            },
            {
                "quantity": "10",
                "price": 1449.0,
                "whishlist_status": "Login Required",
                "variant_id": 5613,
                "variant_name": "Nokia 105 Dual Sim  (Black)",
                "actual_price": 1449.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/nokia_105_black_tFe7CMs.jpg",
                "color_variant_id": 1401,
                "color_variant_name": "Black ",
                "storage_variant_id": "",
                "storage_variant_name": "",
                "other_variant_id": "",
                "other_variant_name": "",
                "stock_sataus": "In-stock",
                "id": 3414,
                "Meta_Title": "meta_tag_title",
                "Meta_Keyword": "meta_tag_keywords\n",
                "Meta_Description": "meta_tag_description",
                "title": "Nokia 105 TA-1459 DS",
                "HSN": "85171400",
                "description": "The Nokia 105 DS feature phone will take you on a trip down memory lane, where your phone was used for basic communication purposes and the occasional game of Snake. This phone is ergonomically designed with an Island Keymat that lets you type and dial easily. It also offers up to 15 hours of talk time to let you have endless conversations with your dear one.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2023-10-27T17:36:36.269816",
                "permission": 1,
                "slug": "nokia-105-ta-1459-ds",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 191,
                "sub_category": "Nokia",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 231,
                "brand_name": "Nokia",
                "store_id": 1
            },
            {
                "quantity": "10",
                "price": 1449.0,
                "whishlist_status": "Login Required",
                "variant_id": 5614,
                "variant_name": "Nokia 105 Dual Sim  (Charcoal)",
                "actual_price": 1449.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/NOKIA_105_CHARCOAL_NFU9IcS.jpg",
                "color_variant_id": 1549,
                "color_variant_name": "Charcoal",
                "storage_variant_id": "",
                "storage_variant_name": "",
                "other_variant_id": "",
                "other_variant_name": "",
                "stock_sataus": "In-stock",
                "id": 3414,
                "Meta_Title": "meta_tag_title",
                "Meta_Keyword": "meta_tag_keywords\n",
                "Meta_Description": "meta_tag_description",
                "title": "Nokia 105 TA-1459 DS",
                "HSN": "85171400",
                "description": "The Nokia 105 DS feature phone will take you on a trip down memory lane, where your phone was used for basic communication purposes and the occasional game of Snake. This phone is ergonomically designed with an Island Keymat that lets you type and dial easily. It also offers up to 15 hours of talk time to let you have endless conversations with your dear one.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2023-10-27T17:36:36.269816",
                "permission": 1,
                "slug": "nokia-105-ta-1459-ds",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 191,
                "sub_category": "Nokia",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 231,
                "brand_name": "Nokia",
                "store_id": 1
            },
            {
                "quantity": "10",
                "price": 1449.0,
                "whishlist_status": "Login Required",
                "variant_id": 5615,
                "variant_name": "Nokia 105 Dual Sim  (Pink)",
                "actual_price": 1449.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/nokia_105_pink_rYOUBRq.jpg",
                "color_variant_id": 1495,
                "color_variant_name": "Pink",
                "storage_variant_id": "",
                "storage_variant_name": "",
                "other_variant_id": "",
                "other_variant_name": "",
                "stock_sataus": "In-stock",
                "id": 3414,
                "Meta_Title": "meta_tag_title",
                "Meta_Keyword": "meta_tag_keywords\n",
                "Meta_Description": "meta_tag_description",
                "title": "Nokia 105 TA-1459 DS",
                "HSN": "85171400",
                "description": "The Nokia 105 DS feature phone will take you on a trip down memory lane, where your phone was used for basic communication purposes and the occasional game of Snake. This phone is ergonomically designed with an Island Keymat that lets you type and dial easily. It also offers up to 15 hours of talk time to let you have endless conversations with your dear one.",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2023-10-27T17:36:36.269816",
                "permission": 1,
                "slug": "nokia-105-ta-1459-ds",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 191,
                "sub_category": "Nokia",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 231,
                "brand_name": "Nokia",
                "store_id": 1
            },
            {
                "quantity": "10",
                "price": 1299.0,
                "whishlist_status": "Login Required",
                "variant_id": 5616,
                "variant_name": "Nokia 105 Single Sim  (Blue)",
                "actual_price": 1299.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/105_blue.jpg",
                "color_variant_id": 1409,
                "color_variant_name": "Blue",
                "storage_variant_id": "",
                "storage_variant_name": "",
                "other_variant_id": "",
                "other_variant_name": "",
                "stock_sataus": "In-stock",
                "id": 3415,
                "Meta_Title": "nan",
                "Meta_Keyword": "nan",
                "Meta_Description": "nan",
                "title": "Nokia 105 TA-1473 SS",
                "HSN": "85171400",
                "description": "nan",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2023-10-27T17:35:00.735160",
                "permission": 1,
                "slug": "nokia-105-ta-1473-ss",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 191,
                "sub_category": "Nokia",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 231,
                "brand_name": "Nokia",
                "store_id": 1
            },
            {
                "quantity": "10",
                "price": 1299.0,
                "whishlist_status": "Login Required",
                "variant_id": 5617,
                "variant_name": "Nokia 105 Single Sim  (Black)",
                "actual_price": 1299.0,
                "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/nokia_105_black.jpg",
                "color_variant_id": 1401,
                "color_variant_name": "Black ",
                "storage_variant_id": "",
                "storage_variant_name": "",
                "other_variant_id": "",
                "other_variant_name": "",
                "stock_sataus": "In-stock",
                "id": 3415,
                "Meta_Title": "nan",
                "Meta_Keyword": "nan",
                "Meta_Description": "nan",
                "title": "Nokia 105 TA-1473 SS",
                "HSN": "85171400",
                "description": "nan",
                "arriving_soon": false,
                "show_for_user": true,
                "is_bestseller": false,
                "admin_permission": "Approved",
                "lastedit_date": "2023-10-27T17:35:00.735160",
                "permission": 1,
                "slug": "nokia-105-ta-1473-ss",
                "main_category_id": 28,
                "main_category": "Mobiles & Tablets",
                "sub_category_id": 191,
                "sub_category": "Nokia",
                "sub_sub_category_id": "",
                "sub_sub_category": "",
                "brand_id": 231,
                "brand_name": "Nokia",
                "store_id": 1
            }
        ]

      
  return (
  <>


  {/* <button   onClick={handleclick} className='px-2 py-2 bg-blue-600  rounded-full  hover:shadow-2xl'>Hamko click karo</button>

  <button onClick={handler} className='px-5 py-5 bg-red-500 rounded-full hover:bg-red-900 hover:shadow-2xl text-black'>Press</button> */}
    {/* <AarayData name={product_list}/> */}
    {/* <Form/> */}
    {/* <Newform/> */}
    {/* <Lastform/> */}
    <Secondform/>
    {/* <Thirdform/> */}
    
  </>
  )
}

export default App
